pipeline:
  name: Gem_POC4
  identifier: Gem_POC4
  projectIdentifier: gemcr
  orgIdentifier: btbt1
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harnessgitconnector
        build: <+input>
  stages:
    - stage:
        name: CI Build
        identifier: CI_Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: Gem_kube
              namespace: ns-aced9b
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - stepGroup:
                  stageType: CI
                  steps:
                    - step:
                        type: Run
                        name: Setup
                        identifier: Setup_Python
                        spec:
                          connectorRef: account.Docker_Remote_GAR
                          image: europe-docker.pkg.dev/dv-sts-psv-tool-svc-bak-08870/staging/docker.io/curlimages/curl:8.11.0
                          shell: Sh
                          command: |
                            cat <<'EOF' > /harness/pip.conf
                            [global]
                            index=https://nexus-osg.tooling01.dev.c2.lloydsbanking.cloud/repository/python-proxy/pypi
                            index-url=https://nexus-osg.tooling01.dev.c2.lloydsbanking.cloud/repository/python-proxy/simple
                            trusted-host=nexus-osg.tooling01.dev.c2.lloydsbanking.cloud
                            cache-dir=/shared/pipcache
                            EOF
                            cat <<'EOF' > /harness/.pypirc
                            [distutils]
                            index-servers =
                                pypi

                            [pypi]
                            repository = https://nexus-osg.tooling01.dev.c2.lloydsbanking.cloud/repository/python-proxy/pypi
                            EOF
                            curl -o /harness/cacert.pem https://dev.vault.02c5d1d0-4e30-4111-bc2f-6a0c7cc5677c.aws.hashicorp.cloud:8200/v1/admin/dev/pki/root/ca/pem
                            file="/harness/pyproject.toml"
                            if [ "<+stepGroup.variables.name_override>" = null ]; then
                              PKG_NAME=$(awk -F'[ ="]+' '$1 == "name" { print $2 }' $file)
                            else
                              PKG_NAME=<+stepGroup.variables.name_override>
                            fi
                            if [ "<+stepGroup.variables.vers_override>" = null ]; then
                              PKG_VERSION=$(awk -F'[ ="]+' '$1 == "version" { print $2 }' $file)
                            else
                              PKG_VERSION=<+stepGroup.variables.vers_override>
                            fi
                          outputVariables:
                            - name: PKG_NAME
                            - name: PKG_VERSION
                          resources:
                            limits:
                              cpu: "1"
                  variables:
                    - name: name_override
                      type: String
                      value: <+input>
                      description: App name override - Required only if not in pyproject.toml, or to override pyproject.toml
                    - name: vers_override
                      type: String
                      value: <+input>
                      description: App version override - Required only if not in pyproject.toml, or to override pyproject.toml
                  name: Init
                  identifier: Init
              - stepGroup:
                  stageType: CI
                  steps:
                    - step:
                        type: Run
                        name: build
                        identifier: build
                        spec:
                          connectorRef: account.Docker_Remote_GAR
                          image: python
                          shell: Sh
                          command: |-
                            export PIP_CONFIG_FILE=/harness/pip.conf
                            pip3 install build
                            <+stepGroup.variables.python_cmd_override>
                          resources:
                            limits:
                              cpu: "1"
                        when:
                          stageStatus: Success
                          condition: <+stepGroup.variables.python_version>==<+matrix.version>
                  strategy:
                    matrix:
                      version:
                        - 3.9.17
                        - 3.10-slim
                        - 3.11
                        - 3.12
                  variables:
                    - name: python_cmd_override
                      type: String
                      value: <+input>.default(python3 -m build)
                      description: Command override - If not specified template will execute `python3 -m build`
                      required: false
                    - name: python_version
                      type: String
                      description: ""
                      required: false
                      value: <+input>.default(3.11).allowedValues(3.9.17,3.10-slim,3.11,3.12)
                  name: PB
                  identifier: PB
